export const SCREEN = {
    AUTH: 'AUTH',
    APP: 'APP',
    SPLASH: 'SPLASH',
    WELCOME: 'WELCOME',
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    NEW_SIGNUP: 'NEW_SIGNUP',
    OTPVERIFICATION: 'OTPVERIFICATION',
    OTP_LOGIN: 'OTP_LOGIN',
    REGISTER: 'REGISTER',
    PASSWORD: 'PASSWORD',
    FORGOTPASSWORD: 'FORGOTPASSWORD',
    RESETSUCCESS: 'RESETSUCCESS',
  
  };
  